using static KatLang.Tests.CountedMatrix.CountedConsumer;
using static KatLang.Tests.CountedMatrix.CountedMatrixCase;
using static KatLang.Tests.CountedMatrix.ProducerCardinality;
using static KatLang.Tests.CountedMatrix.SupplyForm;

namespace KatLang.Tests.CountedMatrix;

/// <summary>
/// Counted-only known-answer matrix across every multi-output consumer.
///
/// <para>KatLang's core cardinality distinction: an ALGORITHM emits zero or
/// more outputs; a SEQUENCE is one value containing zero or more values.
/// Outputs stay separate slots only inside written rows, spread supplies,
/// receiver segments, and loop state; crossing any value boundary (a named
/// reference, call, capture, brace, `if`, structural dot access) turns N
/// outputs into ONE sequence value. Every case here pins, for one consumer and
/// one producer cardinality, how many slots/values must be observed — with the
/// expected answer hand-derived from `lean/KatLang.lean` (each case cites its
/// rule), never recorded from the implementation under test.</para>
///
/// <para>The canonical producer family (<see cref="Producers"/>):
/// <c>P0</c> emits 0 outputs, <c>P1</c> one, <c>P2</c> two, <c>P3</c> three.
/// A named reference to a producer is itself a value boundary — `P2` is ONE
/// sequence value — so cases reach direct multi-output consumption through
/// written rows, explicit spread (`P2*`), written group/brace receivers, and
/// loop state, and contrast each with the captured form.</para>
///
/// <para>Observation is counts and structural cardinality only: the root
/// emitted count plus a value SHAPE with atoms erased (see
/// <see cref="CountedMatrixCase.ShapeOf"/>). Full raw values appear only where
/// the atoms ARE counts (in-language probes such as
/// <c>ArgCount(*args) = args.count</c>) or in the few order sentinels.</para>
/// </summary>
public static class CountedMatrixCorpus
{
    /// <summary>Canonical producers: known output cardinalities 0/1/2/3.</summary>
    public const string Producers =
        "P0 = ()\n" +
        "P1 = 7\n" +
        "P2 = 10, 20\n" +
        "P3 = 1, 2, 3\n";

    /// <summary>Counts the argument slots a call actually received.</summary>
    public const string ArgCount = "ArgCount(*args) = args.count\n";

    private const string P = Producers;
    private const string AC = ArgCount;

    /// <summary>
    /// Consumers that must additionally show an explicit capture-boundary
    /// contrast case (direct multi-output consumption vs consumption after a
    /// written `(...)` boundary). Enforced by the coverage meta-test.
    /// </summary>
    public static readonly IReadOnlyList<CountedConsumer> CaptureContrastConsumers =
    [
        RootOutputRows,
        CaptureBoundary,
        SpreadSupply,
        CallArgumentSlots,
        CollectingParameter,
        ClauseFamilyDispatch,
        DotReceiverSegment,
        BuiltinCollectionView,
        LoopStateSlots,
        IfBoundary,
        ListLiteralSlots,
    ];

    /// <summary>
    /// One host-boundary flattening case: <see cref="Evaluator.RunFlat(Expr)"/>
    /// recursively flattens the root result to numeric atoms (Lean
    /// <c>runFlat</c> / <c>Result.hostAtoms</c>), opening sequence AND list
    /// boundaries. This is the one multi-output consumer that deliberately
    /// ERASES the emission-count distinction, so it gets its own table.
    /// </summary>
    public sealed record HostFlatCase(
        string Id, ProducerCardinality Cardinality, string Source, int ExpectedAtomCount, string Rule);

    public static IReadOnlyList<HostFlatCase> HostFlatCases() =>
    [
        new("host/zero", Zero, P + "P0", 0,
            "a () result flattens to zero host atoms"),
        new("host/spread-empty", Zero, P + "P0*", 0,
            "a zero-output root flattens to zero host atoms"),
        new("host/one", One, P + "P1", 1,
            "one atom output, one host atom"),
        new("host/two-rows", Two, "10, 20", 2,
            "two root outputs flatten to two host atoms"),
        new("host/two-captured", Two, "(10, 20)", 2,
            "flattening erases the emission distinction BY DESIGN: the captured pair also flattens to two atoms"),
        new("host/many-recursive", Many, "[1, [2, 3]]", 3,
            "host flattening opens list boundaries recursively (Result.hostAtoms), unlike every in-language view"),
    ];

    public static IReadOnlyList<CountedMatrixCase> Cases() =>
    [
        // ── Root output rows ─────────────────────────────────────────────────
        // evalOutputRowsPreparedCore: non-spread row = one visible slot, emitted
        // += max(1, count); spread row = its supply items, emitted += count.
        Shape("root/named-zero", RootOutputRows, Zero, NamedReference,
            P + "P0",
            "S[]", 1,
            "a non-spread row is one visible slot even for () — emitted clamps to 1 (evalOutputRowsPreparedCore)"),
        Shape("root/named-one", RootOutputRows, One, NamedReference,
            P + "P1",
            "#", 1,
            "one atom row emits one output"),
        Shape("root/named-two", RootOutputRows, Two, NamedReference,
            P + "P2",
            "S[#, #]", 1,
            "a named reference is a value boundary: two body outputs arrive as ONE sequence value (evalCounted .resolve re-counts)"),
        Shape("root/named-many", RootOutputRows, Many, NamedReference,
            P + "P3",
            "S[#, #, #]", 1,
            "named N-output producer is one sequence value at the reference"),
        Shape("root/rows-two", RootOutputRows, Two, WrittenRows,
            "10, 20",
            "S[#, #]", 2,
            "two written root slots emit two outputs — same value structure as (10, 20) but emitted count 2"),
        Shape("root/rows-many", RootOutputRows, Many, WrittenRows,
            "1, 2, 3",
            "S[#, #, #]", 3,
            "three written root slots emit three outputs"),
        Shape("root/rows-newlines", RootOutputRows, Two, WrittenRows,
            "10\n20",
            "S[#, #]", 2,
            "a newline separates root output slots exactly like a comma"),
        Shape("root/written-empty", RootOutputRows, Zero, WrittenRows,
            "()",
            "S[]", 1,
            "a written () row is one visible empty output slot"),
        Shape("root/spread-zero", RootOutputRows, Zero, SpreadMarker,
            P + "P0*",
            "S[]", 0,
            "only an explicit spread can contribute zero root outputs (spread of () supplies no items)"),
        Shape("root/spread-one", RootOutputRows, One, SpreadMarker,
            P + "P1*",
            "#", 1,
            "spread is total: an atom supplies itself as one item"),
        Shape("root/spread-two", RootOutputRows, Two, SpreadMarker,
            P + "P2*",
            "S[#, #]", 2,
            "spreading the named producer re-opens its value boundary: two outputs again"),
        Shape("root/spread-many", RootOutputRows, Many, SpreadMarker,
            P + "P3*",
            "S[#, #, #]", 3,
            "spread of a three-item sequence emits three root outputs"),
        Shape("root/combo-zero-then-one", RootOutputRows, Combo, NamedReference,
            P + "P0, P1",
            "S[S[], #]", 2,
            "a () slot beside another row stays a visible slot: two outputs, first empty"),
        Shape("root/combo-one-then-zero", RootOutputRows, Combo, NamedReference,
            P + "P1, P0",
            "S[#, S[]]", 2,
            "zero-output producer AFTER another row is still one visible slot"),
        Shape("root/combo-zero-zero", RootOutputRows, Combo, NamedReference,
            P + "P0, P0",
            "S[S[], S[]]", 2,
            "two () rows are two visible empty slots"),
        Shape("root/combo-zero-between", RootOutputRows, Combo, NamedReference,
            P + "P1, P0, P2",
            "S[#, S[], S[#, #]]", 3,
            "a zero-output producer BETWEEN producers occupies its own slot"),
        Shape("root/combo-spread-mix", RootOutputRows, Combo, SpreadMarker,
            P + "P0*, P2*, P1*",
            "S[#, #, #]", 3,
            "adjacent spread rows concatenate their supplies: 0 + 2 + 1 = 3 outputs"),
        Shape("root/projection-row", RootOutputRows, Two, WrittenRows,
            "S = ((1, 2), (3, 4))\nS:0",
            "S[#, #]", 2,
            "an index projection re-emits the projected item count through one root row (Result.select?)"),
        Shape("root/projection-row-parens-unwrap", RootOutputRows, Two, CaptureWrapped,
            "S = ((1, 2), (3, 4))\n(S:0)",
            "S[#, #]", 2,
            "single-expression parens around an index expression are pure grouping — the parser unwraps them (ShouldUnwrapParenthesizedPrimary), so the projection still emits 2"),
        Shape("root/projection-row-brace-captured", RootOutputRows, Two, BraceWrapped,
            "S = ((1, 2), (3, 4))\n{S:0}",
            "S[#, #]", 1,
            "a brace IS a value boundary: the same projection arrives as one value — same structure, emitted count 1"),
        Shape("root/projection-row-named-captured", RootOutputRows, Two, NamedReference,
            "S = ((1, 2), (3, 4))\nB = S:0\nB",
            "S[#, #]", 1,
            "binding the projection also captures it: the named reference emits one value"),
        Raw("root/order-sentinel", RootOutputRows, Combo, SpreadMarker,
            P + "P2*, P1*, P3*",
            "S[10, 20, 7, 1, 2, 3]", 6,
            "ORDER SENTINEL: spread rows contribute left to right in written order"),

        // ── Definition body capture ──────────────────────────────────────────
        Raw("def/body-rows-and-spread", DefinitionBodyCapture, Many, SpreadMarker,
            P + "X = P2*, P1\nX.count",
            "3", 1,
            "body rows accumulate like output rows (spread splices), then the name captures them as one sequence"),
        Raw("def/visible-empty-slot", DefinitionBodyCapture, Combo, NamedReference,
            P + "Y = P0, P1\nY.count",
            "2", 1,
            "a () body slot stays a visible item of the captured sequence"),
        Raw("def/spread-empty-body", DefinitionBodyCapture, Zero, SpreadMarker,
            P + "Z = P0*\nZ.count",
            "0", 1,
            "a body that spreads () captures the empty sequence value"),
        Raw("def/one", DefinitionBodyCapture, One, WrittenRows,
            "W1 = 7\nW1.count",
            "1", 1,
            "a one-output body captures one value"),
        Raw("def/two", DefinitionBodyCapture, Two, WrittenRows,
            "W2 = 10, 20\nW2.count",
            "2", 1,
            "a two-output body captures a two-item sequence"),

        // ── Capture boundary (...) ───────────────────────────────────────────
        Shape("cap/spread-empty", CaptureBoundary, Zero, SpreadMarker,
            P + "(P0*)",
            "S[]", 1,
            "capture of an empty supply is the empty sequence value"),
        Shape("cap/singleton-empty", CaptureBoundary, Zero, NamedReference,
            P + "(P0)",
            "S[]", 1,
            "a single slot passes through combineOutputSlots unwrapped: (P0) is ()"),
        Shape("cap/one", CaptureBoundary, One, NamedReference,
            P + "(P1)",
            "#", 1,
            "a singleton capture is the item itself (no orphan wrapper)"),
        Shape("cap/pair-written", CaptureBoundary, Two, WrittenRows,
            "(10, 20)",
            "S[#, #]", 1,
            "two written slots capture as ONE two-item sequence value"),
        Shape("cap/pair-spread", CaptureBoundary, Two, SpreadMarker,
            P + "(P2*)",
            "S[#, #]", 1,
            "a spread slot splices its supply into the capture, still one value outside"),
        Shape("cap/named-slots-opaque", CaptureBoundary, Two, NamedReference,
            P + "(P2, P2)",
            "S[S[#, #], S[#, #]]", 1,
            "each non-spread written slot reifies to exactly one value: no flattening of named sequence producers"),
        Shape("cap/many", CaptureBoundary, Many, SpreadMarker,
            P + "(P2*, P1)",
            "S[#, #, #]", 1,
            "spliced and reified slots concatenate inside one captured sequence"),
        Shape("cap/visible-empty-slot", CaptureBoundary, Combo, NamedReference,
            P + "(P0, P1)",
            "S[S[], #]", 1,
            "a () written slot stays a visible sequence item"),
        Shape("cap/double-empty", CaptureBoundary, Combo, WrittenRows,
            "((), ())",
            "S[S[], S[]]", 1,
            "two written () slots are two items of one sequence"),
        Shape("cap/unary-empty-canonical", CaptureBoundary, Zero, WrittenRows,
            "(())",
            "S[]", 1,
            "redundant unary sequence structure canonicalizes: (()) is ()"),
        Raw("cap/length-probe", CaptureBoundary, Two, CaptureWrapped,
            P + "count((P2, P2))",
            "2", 1,
            "the captured sequence's length equals its written slot count"),
        Shape("cap/spreads-of-empty", CaptureBoundary, Combo, SpreadMarker,
            P + "(P0*, P0*)",
            "S[]", 1,
            "spread slots of () contribute nothing: the capture is empty"),

        // ── Brace algorithm value boundary {...} ─────────────────────────────
        Shape("brace/zero", BraceValueBoundary, Zero, BraceWrapped,
            "{()}",
            "S[]", 1,
            "a brace whose body emits () is one visible empty value at the value boundary"),
        Shape("brace/one", BraceValueBoundary, One, BraceWrapped,
            "{7}",
            "#", 1,
            "one brace output crosses the boundary as itself"),
        Shape("brace/two", BraceValueBoundary, Two, BraceWrapped,
            "{10, 20}",
            "S[#, #]", 1,
            "two brace outputs become ONE sequence value at the value boundary (evalCounted .algorithmExpr re-counts)"),
        Shape("brace/many-scoped", BraceValueBoundary, Many, BraceWrapped,
            "{A = 1\nA + 1, A + 2, A + 3}",
            "S[#, #, #]", 1,
            "local properties emit nothing; three output rows become one sequence value"),
        Shape("brace/spread-reopens", BraceValueBoundary, Two, SpreadMarker,
            "{10, 20}*",
            "S[#, #]", 2,
            "explicit spread re-opens the brace's value boundary: two outputs again"),
        Shape("brace/nested", BraceValueBoundary, Two, Nested,
            "{ {10, 20}, 5 }",
            "S[S[#, #], #]", 1,
            "an inner brace is one value slot of the outer brace's output"),

        // ── Spread supply expr* ──────────────────────────────────────────────
        Shape("spread/atom-total", SpreadSupply, One, WrittenRows,
            "7*",
            "#", 1,
            "spread is total: an atom supplies itself as one item"),
        Shape("spread/string-total", SpreadSupply, One, WrittenRows,
            "'ab'*",
            "$", 1,
            "a string supplies itself as one item — strings never open"),
        Shape("spread/empty", SpreadSupply, Zero, NamedReference,
            P + "P0*",
            "S[]", 0,
            "spread of () supplies zero items"),
        Shape("spread/list-opens", SpreadSupply, Two, WrittenRows,
            "[10, 20]*",
            "S[#, #]", 2,
            "spread opens exactly one boundary: a list supplies its elements (the list boundary is consumed)"),
        Shape("spread/list-empty", SpreadSupply, Zero, WrittenRows,
            "[]*",
            "S[]", 0,
            "spread of [] supplies zero items — the empty list opens to an empty supply"),
        Shape("spread/captured-operand", SpreadSupply, Two, CaptureWrapped,
            P + "(P2)*",
            "S[#, #]", 2,
            "grouping the operand adds no boundary: (P2)* spreads the same value as P2*"),
        Shape("spread/chained-fixed-point", SpreadSupply, Many, WrittenRows,
            "[[1, 2], [3, 4]]**",
            "S[L[#, #], L[#, #]]", 2,
            "chained spread is compositional, not recursive: a multi-item supply is a fixed point (peelSequenceSpreadLayers)"),
        Raw("spread/chained-singleton-opens", SpreadSupply, One, WrittenRows,
            "[[7]]**",
            "7", 1,
            "only a lone structured item opens one more boundary per extra written star: [[7]]** supplies 7"),
        Shape("spread/double-star-seq", SpreadSupply, Two, NamedReference,
            P + "P2**",
            "S[#, #]", 2,
            "a two-item sequence supply re-captures to the same sequence: extra stars are fixed points"),
        Err("spread/missing-output", SpreadSupply, Zero, BraceWrapped,
            "{A = 1}*",
            "spreadMissingOutput",
            "spreading an operand with no defined output is the spread-specific error (evalSequenceSpreadOperandItems)"),

        // ── Call argument slots (shared assembly) ────────────────────────────
        // ArgCount(*args) = args.count observes exactly how many argument slots
        // the call received (collect wraps precisely the assigned slots).
        Raw("args/none", CallArgumentSlots, Zero, WrittenRows,
            AC + "ArgCount()",
            "0", 1,
            "an empty argument list supplies zero slots"),
        Raw("args/named-empty-is-one", CallArgumentSlots, Zero, NamedReference,
            P + AC + "ArgCount(P0)",
            "1", 1,
            "a written slot reifies to exactly ONE argument even when its value is ()"),
        Raw("args/spread-empty-is-zero", CallArgumentSlots, Zero, SpreadMarker,
            P + AC + "ArgCount(P0*)",
            "0", 1,
            "an explicit spread of () supplies zero argument slots"),
        Raw("args/one", CallArgumentSlots, One, NamedReference,
            P + AC + "ArgCount(P1)",
            "1", 1,
            "one producer output, one slot"),
        Raw("args/spread-one", CallArgumentSlots, One, SpreadMarker,
            P + AC + "ArgCount(P1*)",
            "1", 1,
            "spreading an atom supplies the same single slot"),
        Raw("args/named-two-is-one", CallArgumentSlots, Two, NamedReference,
            P + AC + "ArgCount(P2)",
            "1", 1,
            "a named two-output producer is ONE argument (value boundary); no implicit opening"),
        Raw("args/spread-two", CallArgumentSlots, Two, SpreadMarker,
            P + AC + "ArgCount(P2*)",
            "2", 1,
            "explicit spread expands one value boundary into two argument slots"),
        Raw("args/spread-many", CallArgumentSlots, Many, SpreadMarker,
            P + AC + "ArgCount(P3*)",
            "3", 1,
            "spread of a three-item sequence supplies three slots"),
        Raw("args/captured-two-is-one", CallArgumentSlots, Two, CaptureWrapped,
            AC + "ArgCount((10, 20))",
            "1", 1,
            "a capture is one argument slot containing one sequence value"),
        Raw("args/brace-two-is-one", CallArgumentSlots, Two, BraceWrapped,
            AC + "ArgCount({10, 20})",
            "1", 1,
            "a zero-declaration brace argument reifies at the one-slot value boundary"),
        Raw("args/list-is-one", CallArgumentSlots, Many, WrittenRows,
            AC + "ArgCount([1, 2, 3])",
            "1", 1,
            "a list value is one argument; calls never open lists implicitly"),
        Raw("args/string-is-one", CallArgumentSlots, One, WrittenRows,
            AC + "ArgCount('ab')",
            "1", 1,
            "a string is one argument slot"),
        Raw("args/combo-p0-p0", CallArgumentSlots, Combo, NamedReference,
            P + AC + "ArgCount(P0, P0)",
            "2", 1,
            "two written slots are two arguments regardless of their values"),
        Raw("args/combo-p0-p1", CallArgumentSlots, Combo, NamedReference,
            P + AC + "ArgCount(P0, P1)",
            "2", 1, "slot count is written count: (P0, P1) is two arguments"),
        Raw("args/combo-p1-p0", CallArgumentSlots, Combo, NamedReference,
            P + AC + "ArgCount(P1, P0)",
            "2", 1, "slot count is written count: (P1, P0) is two arguments"),
        Raw("args/combo-p1-p1", CallArgumentSlots, Combo, NamedReference,
            P + AC + "ArgCount(P1, P1)",
            "2", 1, "two one-output producers, two slots"),
        Raw("args/combo-p1-p2", CallArgumentSlots, Combo, NamedReference,
            P + AC + "ArgCount(P1, P2)",
            "2", 1, "a named two-output producer beside an atom is still one slot each"),
        Raw("args/combo-p2-p1", CallArgumentSlots, Combo, NamedReference,
            P + AC + "ArgCount(P2, P1)",
            "2", 1, "order does not change slot counting"),
        Raw("args/combo-p2-p2", CallArgumentSlots, Combo, NamedReference,
            P + AC + "ArgCount(P2, P2)",
            "2", 1, "two named producers, two slots"),
        Raw("args/combo-p0-p2-p1", CallArgumentSlots, Combo, NamedReference,
            P + AC + "ArgCount(P0, P2, P1)",
            "3", 1, "three written slots including a () slot are three arguments"),
        Raw("args/combo-spread-zero-zero", CallArgumentSlots, Combo, SpreadMarker,
            P + AC + "ArgCount(P0*, P0*)",
            "0", 1, "adjacent empty spreads concatenate to zero slots"),
        Raw("args/combo-spread-zero-one", CallArgumentSlots, Combo, SpreadMarker,
            P + AC + "ArgCount(P0*, P1*)",
            "1", 1, "0 + 1 spread items concatenate to one slot"),
        Raw("args/combo-spread-one-zero", CallArgumentSlots, Combo, SpreadMarker,
            P + AC + "ArgCount(P1*, P0*)",
            "1", 1, "1 + 0 spread items concatenate to one slot"),
        Raw("args/combo-spread-one-one", CallArgumentSlots, Combo, SpreadMarker,
            P + AC + "ArgCount(P1*, P1*)",
            "2", 1, "1 + 1 spread items concatenate to two slots"),
        Raw("args/combo-spread-one-two", CallArgumentSlots, Combo, SpreadMarker,
            P + AC + "ArgCount(P1*, P2*)",
            "3", 1, "1 + 2 spread items concatenate to three slots"),
        Raw("args/combo-spread-two-one", CallArgumentSlots, Combo, SpreadMarker,
            P + AC + "ArgCount(P2*, P1*)",
            "3", 1, "2 + 1 spread items concatenate to three slots"),
        Raw("args/combo-spread-two-two", CallArgumentSlots, Combo, SpreadMarker,
            P + AC + "ArgCount(P2*, P2*)",
            "4", 1, "2 + 2 spread items concatenate to four slots"),
        Raw("args/combo-spread-zero-two-one", CallArgumentSlots, Combo, SpreadMarker,
            P + AC + "ArgCount(P0*, P2*, P1*)",
            "3", 1, "0 + 2 + 1 spread items concatenate to three slots"),
        Raw("args/combo-mixed-named-spread", CallArgumentSlots, Combo, SpreadMarker,
            P + AC + "ArgCount(P2, P2*)",
            "3", 1, "a reified slot and a spread slot mix: 1 + 2 = 3 arguments"),

        // ── Fixed-arity binding ──────────────────────────────────────────────
        Err("fixed/named-two-is-one-arg", FixedArityBinding, Two, NamedReference,
            P + "Two(a, b) = 77\nTwo(P2)",
            "arity",
            "a named two-output producer is one argument and cannot satisfy two fixed parameters"),
        Raw("fixed/spread-two-fills", FixedArityBinding, Two, SpreadMarker,
            P + "Two(a, b) = 77\nTwo(P2*)",
            "77", 1,
            "spreading the producer supplies exactly the two required slots"),
        Raw("fixed/empty-arg-binds", FixedArityBinding, Zero, NamedReference,
            P + "Two(a, b) = 77\nTwo(P0, P1)",
            "77", 1,
            "a () argument binds a fixed parameter like any other single value"),
        Err("fixed/spread-empty-underflow", FixedArityBinding, Zero, SpreadMarker,
            P + "Two(a, b) = 77\nTwo(P0*, P1)",
            "arity",
            "a spread of () vanishes before arity checking: 0 + 1 slots underflow two parameters"),
        Err("fixed/spread-many-overflow", FixedArityBinding, Many, SpreadMarker,
            P + "Two(a, b) = 77\nTwo(P3*)",
            "arity",
            "three spread slots overflow two fixed parameters"),
        Shape("fixed/identity-empty", FixedArityBinding, Zero, NamedReference,
            P + "One1(a) = a\nOne1(P0)",
            "S[]", 1,
            "() binds, flows through the body, and returns as one visible empty value"),
        Shape("fixed/identity-two", FixedArityBinding, Two, NamedReference,
            P + "One1(a) = a\nOne1(P2)",
            "S[#, #]", 1,
            "the bound sequence stays one value through parameter and result boundaries"),
        Raw("fixed/identity-one", FixedArityBinding, One, NamedReference,
            P + "One1(a) = a\nOne1(P1)",
            "7", 1,
            "one output in, one value bound, one value out"),

        // ── Collecting parameter (exact list) ────────────────────────────────
        Shape("collect/exact-empty", CollectingParameter, Zero, WrittenRows,
            "Items(*i) = i\nItems()",
            "L[]", 1,
            "zero assigned slots collect the empty exact list (collectSegment [] = [])"),
        Shape("collect/exact-single-empty", CollectingParameter, Zero, NamedReference,
            P + "Items(*i) = i\nItems(P0)",
            "L[S[]]", 1,
            "one () slot collects [()], never erased — F(()) and F(()*) stay observably different"),
        Shape("collect/exact-one", CollectingParameter, One, NamedReference,
            P + "Items(*i) = i\nItems(P1)",
            "L[#]", 1,
            "one slot collects a one-element list"),
        Shape("collect/exact-two-spread", CollectingParameter, Two, SpreadMarker,
            P + "Items(*i) = i\nItems(P2*)",
            "L[#, #]", 1,
            "two spread slots collect a two-element list"),
        Shape("collect/exact-seq-opaque", CollectingParameter, Two, NamedReference,
            P + "Items(*i) = i\nItems(P2)",
            "L[S[#, #]]", 1,
            "a named producer is one collected slot holding the whole sequence"),
        Shape("collect/exact-captured", CollectingParameter, Two, CaptureWrapped,
            "Items(*i) = i\nItems((10, 20))",
            "L[S[#, #]]", 1,
            "a captured pair is one collected slot"),
        Shape("collect/exact-many-mixed", CollectingParameter, Many, NamedReference,
            P + "Items(*i) = i\nItems(P0, P2, P1)",
            "L[S[], S[#, #], #]", 1,
            "collect stores exactly the assigned slots in order, () included"),

        // ── Mixed prefix/collecting/suffix parameter list ────────────────────
        Raw("mixed/zero-middle", MixedParameterList, Zero, WrittenRows,
            "Mid(first, *mid, last) = mid.count\nMid(1, 2)",
            "0", 1,
            "fixed ends bind front and back; the collecting middle may collect zero slots"),
        Raw("mixed/one-middle", MixedParameterList, One, WrittenRows,
            "Mid(first, *mid, last) = mid.count\nMid(1, 2, 3)",
            "1", 1,
            "one middle slot collects a one-element list"),
        Raw("mixed/two-middle", MixedParameterList, Two, WrittenRows,
            "Mid(first, *mid, last) = mid.count\nMid(1, 2, 3, 4)",
            "2", 1,
            "two middle slots collect two elements"),
        Raw("mixed/many-middle-spread", MixedParameterList, Many, SpreadMarker,
            P + "Mid(first, *mid, last) = mid.count\nMid(P3*, P3*)",
            "4", 1,
            "six spread slots allocate one front, one back, four middle"),
        Err("mixed/underflow", MixedParameterList, One, WrittenRows,
            "Mid(first, *mid, last) = mid.count\nMid(1)",
            "arity",
            "one slot cannot satisfy two fixed ends"),
        Raw("mixed/empty-ends", MixedParameterList, Zero, NamedReference,
            P + "Mid(first, *mid, last) = mid.count\nMid(P0, P0)",
            "0", 1,
            "() slots bind the fixed ends; the middle collects zero"),

        // ── Collecting forwarding (spread of a collected list) ───────────────
        Raw("fwd/zero", CollectingForwarding, Zero, WrittenRows,
            AC + "Fwd(*items) = ArgCount(items*)\nFwd()",
            "0", 1,
            "spread(collect xs) = xs: zero collected slots forward zero arguments"),
        Raw("fwd/one", CollectingForwarding, One, WrittenRows,
            AC + "Fwd(*items) = ArgCount(items*)\nFwd(7)",
            "1", 1,
            "one collected slot forwards one argument"),
        Raw("fwd/empty-item-roundtrip", CollectingForwarding, Zero, NamedReference,
            P + AC + "Fwd(*items) = ArgCount(items*)\nFwd(P0)",
            "1", 1,
            "a collected () slot round-trips as one argument — [()]* supplies the () item"),
        Raw("fwd/two", CollectingForwarding, Two, SpreadMarker,
            P + AC + "Fwd(*items) = ArgCount(items*)\nFwd(P2*)",
            "2", 1,
            "two collected slots forward two arguments"),
        Raw("fwd/many", CollectingForwarding, Many, WrittenRows,
            AC + "Fwd(*items) = ArgCount(items*)\nFwd(1, 2, 3)",
            "3", 1,
            "three collected slots forward three arguments"),
        Raw("fwd/unspread-is-one", CollectingForwarding, Many, WrittenRows,
            AC + "Pass(*items) = ArgCount(items)\nPass(1, 2, 3)",
            "1", 1,
            "passing the collected list unspread passes ONE list argument"),
        Raw("fwd/order-sentinel", CollectingForwarding, Combo, SpreadMarker,
            P + "FwdAll(*items) = items\nFwdAll(P2*, 7)",
            "L[10, 20, 7]", 1,
            "ORDER SENTINEL: collect preserves assigned slot order exactly"),

        // ── Assignment deconstruction ────────────────────────────────────────
        Raw("dec/middle-zero", DeconstructionBinding, Zero, CaptureWrapped,
            "x, *y, z = (1, 2)\ny.count",
            "0", 1,
            "the RHS opens one structure boundary; the collecting middle may be empty"),
        Raw("dec/middle-one", DeconstructionBinding, One, CaptureWrapped,
            "x, *y, z = (1, 2, 3)\ny.count",
            "1", 1,
            "three items allocate one middle element"),
        Raw("dec/middle-two", DeconstructionBinding, Two, CaptureWrapped,
            "x, *y, z = (1, 2, 3, 4)\ny.count",
            "2", 1,
            "four items allocate two middle elements"),
        Raw("dec/middle-many", DeconstructionBinding, Many, CaptureWrapped,
            "x, *y, z = (1, 2, 3, 4, 5)\ny.count",
            "3", 1,
            "five items allocate three middle elements"),
        Raw("dec/list-opens", DeconstructionBinding, Many, WrittenRows,
            "x, *y, z = [1, 2, 3]\ny.count",
            "1", 1,
            "deconstruction opens a lone LIST boundary exactly like a lone sequence (structureItems?)"),
        Raw("dec/scalar-one-item", DeconstructionBinding, One, WrittenRows,
            "x, *y = 1\ny.count",
            "0", 1,
            "a scalar RHS is one item by the scalar one-item rule: x = 1, y = []"),
        Err("dec/overflow", DeconstructionBinding, Many, CaptureWrapped,
            "x, y = (1, 2, 3)\nx",
            "arity",
            "three items cannot bind two fixed targets"),
        Raw("dec/named-rhs-opens", DeconstructionBinding, Two, NamedReference,
            P + "x, y = P2\nx + y",
            "30", 1,
            "a stored sequence value opens element-by-element: unpacking is deconstruction-specific"),
        Raw("dec/spread-rhs-singleton-list", DeconstructionBinding, Two, SpreadMarker,
            "x, y = [(1, 2)]*\ny",
            "2", 1,
            "a spread RHS re-captures first, so the lone structured element opens one level further"),
        Err("dec/bare-singleton-list", DeconstructionBinding, Two, WrittenRows,
            "x, y = [(1, 2)]\nx",
            "arity",
            "without the spread, the list opens to ONE element which cannot bind two targets"),
        Raw("dec/lone-collecting-empty", DeconstructionBinding, Zero, NamedReference,
            P + "*y = P0\ny.count",
            "0", 1,
            "a lone collecting target over () collects the empty list"),

        // ── Sequence-value parameter pattern F((a, *b)) ──────────────────────
        Err("svp/empty-arg", SequenceValuePattern, Zero, WrittenRows,
            "G((a, *b)) = b.count\nG(())",
            "arity",
            "() opens to zero items, which cannot bind the fixed head"),
        Raw("svp/scalar-one-item", SequenceValuePattern, One, WrittenRows,
            "G((a, *b)) = b.count\nG(7)",
            "0", 1,
            "a scalar argument is one item: a = 7, b = []"),
        Raw("svp/two", SequenceValuePattern, Two, CaptureWrapped,
            "G((a, *b)) = b.count\nG((1, 2))",
            "1", 1,
            "a two-item sequence binds head + one collected item"),
        Raw("svp/many", SequenceValuePattern, Many, CaptureWrapped,
            "G((a, *b)) = b.count\nG((1, 2, 3, 4))",
            "3", 1,
            "four items bind head + three collected"),
        Raw("svp/list-opens", SequenceValuePattern, Many, WrittenRows,
            "G((a, *b)) = b.count\nG([1, 2, 3])",
            "2", 1,
            "the pattern opens a received exact list exactly like a sequence"),
        Raw("svp/named", SequenceValuePattern, Two, NamedReference,
            P + "G((a, *b)) = b.count\nG(P2)",
            "1", 1,
            "a named producer's captured sequence opens through the pattern"),
        Err("svp/singleton-opens-structure", SequenceValuePattern, Two, CaptureWrapped,
            "H((x)) = x\nH((1, 2))",
            "arity",
            "a SINGLE-clause singleton pattern is a deconstruction receiver: it opens the structure, so two items overflow one binding — contrast clause/singleton-pattern-whole-list"),

        // ── Multi-clause conditional dispatch ────────────────────────────────
        // The front end requires UNIFORM top-level pattern arity across a
        // family's clauses, so cardinality mismatches surface at the CALL:
        // spread expands first, then a call whose argument count differs from
        // the family arity matches no clause (Lean matchCallBranches).
        Raw("clause/spread-selects-literal-pair", ClauseFamilyDispatch, Two, SpreadMarker,
            "D(0, 0) = 111\nD(x, y) = 222\nZ2 = 0, 0\nD(Z2*)",
            "111", 1,
            "spread expands BEFORE clause selection: the literal pair clause wins on a spread (0, 0)"),
        Raw("clause/spread-selects-catch-all", ClauseFamilyDispatch, Two, SpreadMarker,
            P + "D(0, 0) = 111\nD(x, y) = 222\nD(P2*)",
            "222", 1,
            "a spread non-matching pair falls to the two-argument binder clause"),
        Err("clause/seq-is-one-arg", ClauseFamilyDispatch, Two, NamedReference,
            "D(0, 0) = 111\nD(x, y) = 222\nZ2 = 0, 0\nD(Z2)",
            "branch",
            "unspread, the sequence is ONE argument, and a two-argument family has no clause for it"),
        Err("clause/captured-pair-is-one-arg", ClauseFamilyDispatch, Two, CaptureWrapped,
            "D(0, 0) = 111\nD(x, y) = 222\nD((0, 0))",
            "branch",
            "a captured pair is one argument for clause selection"),
        Raw("clause/empty-selects-catch-all", ClauseFamilyDispatch, Zero, NamedReference,
            P + "C(0) = 111\nC(x) = 222\nC(P0)",
            "222", 1,
            "a () argument is one argument and selects the one-argument binder clause"),
        Raw("clause/one-seq-arg-selects-catch-all", ClauseFamilyDispatch, Two, NamedReference,
            P + "C(0) = 111\nC(x) = 222\nC(P2)",
            "222", 1,
            "one sequence argument binds the catch-all whole"),
        Err("clause/spread-pair-overflows-catch-all", ClauseFamilyDispatch, Combo, SpreadMarker,
            P + "C(0) = 111\nC(x) = 222\nC(P2*)",
            "branch",
            "a one-argument catch-all never absorbs a spread pair"),
        Err("clause/spread-empty-no-branch", ClauseFamilyDispatch, Zero, SpreadMarker,
            P + "C(0) = 111\nC(x) = 222\nC(P0*)",
            "branch",
            "zero arguments after spreading match no clause"),
        Err("clause/many-no-branch", ClauseFamilyDispatch, Many, SpreadMarker,
            P + "D(0, 0) = 111\nD(x, y) = 222\nD(P3*)",
            "branch",
            "three spread arguments match no two-argument clause"),
        Shape("clause/result-boundary", ClauseFamilyDispatch, Two, WrittenRows,
            "W(0) = 10, 20\nW(0)",
            "S[#, #]", 1,
            "a clause body's two outputs cross the call boundary as one sequence value"),
        Raw("clause/singleton-pattern-whole-list", ClauseFamilyDispatch, One, WrittenRows,
            "E((x)) = x.count\nE(0) = 999\nE([1, 2])",
            "2", 1,
            "in a clause FAMILY the singleton pattern (x) matches any ONE argument whole, binding the entire list (matchCallPattern)"),
        Raw("clause/singleton-pattern-scalar", ClauseFamilyDispatch, One, WrittenRows,
            "E((x)) = x.count\nE(0) = 999\nE(7)",
            "1", 1,
            "the family singleton pattern binds a scalar whole"),

        // ── Dot receiver segment ─────────────────────────────────────────────
        Raw("dot/written-group-many", DotReceiverSegment, Many, WrittenRows,
            "Collect(*items) = items.count\n(10, 20, 30).Collect",
            "3", 1,
            "a WRITTEN group receiver supplies its raw row emission to an allocated flat collector"),
        Raw("dot/written-group-empty", DotReceiverSegment, Zero, WrittenRows,
            "Collect(*items) = items.count\n().Collect",
            "0", 1,
            "the written empty group supplies zero items"),
        Raw("dot/written-group-one", DotReceiverSegment, One, WrittenRows,
            "Collect(*items) = items.count\n(7).Collect",
            "1", 1,
            "a one-row group supplies one item"),
        Raw("dot/named-two-supplies-one", DotReceiverSegment, Two, NamedReference,
            P + "Collect(*items) = items.count\nP2.Collect",
            "1", 1,
            "a NAMED receiver evaluates at its value boundary and supplies ONE item"),
        Raw("dot/named-empty-supplies-zero", DotReceiverSegment, Zero, NamedReference,
            P + "Collect(*items) = items.count\nP0.Collect",
            "0", 1,
            "a named () receiver supplies zero items (valueCount 0)"),
        Raw("dot/captured-empty-supplies-one", DotReceiverSegment, Zero, CaptureWrapped,
            P + "Collect(*items) = items.count\n(P0).Collect",
            "1", 1,
            "parens around a named reference KEEP a capture layer (ShouldUnwrapParenthesizedPrimary): the written group supplies its one visible () row — contrast dot/named-empty-supplies-zero and dot/written-group-empty"),
        Raw("dot/named-one", DotReceiverSegment, One, NamedReference,
            P + "Collect(*items) = items.count\nP1.Collect",
            "1", 1,
            "a named atom receiver supplies one item"),
        Raw("dot/captured-named", DotReceiverSegment, Two, CaptureWrapped,
            P + "Collect(*items) = items.count\n(P2).Collect",
            "1", 1,
            "a capture around a named producer supplies its one written slot"),
        Raw("dot/captured-spread", DotReceiverSegment, Two, CaptureWrapped,
            P + "Collect(*items) = items.count\n(P2*).Collect",
            "2", 1,
            "(P2*) is a capture whose raw supply is the spread items: two"),
        Raw("dot/brace-two", DotReceiverSegment, Two, BraceWrapped,
            "Collect(*items) = items.count\n{10, 20}.Collect",
            "2", 1,
            "a written brace receiver supplies its raw row emission"),
        Raw("dot/fixed-binds-capture", DotReceiverSegment, Two, WrittenRows,
            "Second(a, b) = b\n(10, 20).Second(5)",
            "5", 1,
            "a fixed parameter allocated the receiver segment binds its ONE captured value"),
        Err("dot/one-segment-arity", DotReceiverSegment, Two, WrittenRows,
            "TwoP(a, b) = 1\n(10, 20).TwoP",
            "arity",
            "the receiver is ONE segment: its item count never satisfies arity"),
        Raw("dot/grouped-spread-receiver", DotReceiverSegment, Many, CaptureWrapped,
            P + "Mid2(*mid, last) = (mid.count, last.count)\n(P3*).Mid2",
            "S[0, 3]", 1,
            "(A*).F stays ONE segment: the fixed suffix binds the whole captured value, the collector gets nothing"),
        Shape("dot/structural-zero-arg", DotReceiverSegment, Two, NamedReference,
            "Obj = {V = 10, 20\n0}\nObj.V",
            "S[#, #]", 1,
            "structural zero-arg access is a value boundary (evalDotCallCounted reCountValueBoundary)"),
        Raw("dot/builtin-receiver-empty", DotReceiverSegment, Zero, NamedReference,
            P + "P0.count",
            "0", 1,
            "a named () receiver fills the fixed collection parameter; the view opens it to zero items"),
        Shape("dot/string-intrinsic-atom", DotReceiverSegment, One, NamedReference,
            P + "P1.string",
            "$", 1,
            "the .string intrinsic renders one numeric receiver as one string (resultToString)"),
        Err("dot/string-nonatomic-rejected", DotReceiverSegment, Two, NamedReference,
            P + "P2.string",
            "type",
            "the .string intrinsic expects a numeric receiver: a two-item sequence is rejected (resultToString typeMismatch)"),

        // ── Fluent spread receiver A*.F ──────────────────────────────────────
        Raw("fluent/zero", FluentSpreadReceiver, Zero, SpreadMarker,
            P + "Collect(*items) = items.count\nP0*.Collect",
            "0", 1,
            "A*.F lowers to F(A*): an empty supply is zero argument slots"),
        Raw("fluent/one", FluentSpreadReceiver, One, SpreadMarker,
            P + "Collect(*items) = items.count\nP1*.Collect",
            "1", 1,
            "one supplied item, one argument slot"),
        Raw("fluent/two", FluentSpreadReceiver, Two, SpreadMarker,
            P + "Collect(*items) = items.count\nP2*.Collect",
            "2", 1,
            "two supplied items, two argument slots"),
        Raw("fluent/many", FluentSpreadReceiver, Many, SpreadMarker,
            P + "Collect(*items) = items.count\nP3*.Collect",
            "3", 1,
            "three supplied items, three argument slots"),
        Raw("fluent/vs-grouped-allocation", FluentSpreadReceiver, Many, SpreadMarker,
            P + "Mid2(*mid, last) = (mid.count, last.count)\nP3*.Mid2",
            "S[2, 1]", 1,
            "the fluent form supplies separate slots: the suffix takes the last item, the collector the rest — contrast dot/grouped-spread-receiver"),

        // ── Index projection ─────────────────────────────────────────────────
        Raw("idx/atom", IndexProjection, One, CaptureWrapped,
            "(10, 20, 30):1",
            "20", 1,
            "selecting an atom projects one value"),
        Shape("idx/pair-emission", IndexProjection, Two, NamedReference,
            "S = ((1, 2), (3, 4))\nS:1",
            "S[#, #]", 2,
            "a selected sequence element re-emits its projected item count (projectSelectedContent)"),
        Shape("idx/many-emission", IndexProjection, Many, NamedReference,
            "T = (1, 2, 3), (4, 5, 6)\nT:1",
            "S[#, #, #]", 3,
            "a selected three-item element emits three"),
        Shape("idx/empty-element", IndexProjection, Zero, NamedReference,
            "S2 = (), 5\nS2:0",
            "S[]", 1,
            "a selected () element projects count 0; the root row still shows one visible empty slot"),
        Raw("idx/empty-element-spread-probe", IndexProjection, Zero, SpreadMarker,
            AC + "S2 = (), 5\nArgCount(S2:0*)",
            "0", 1,
            "spreading the empty projection supplies zero slots — the 0-count is real"),
        Raw("idx/empty-element-slot-probe", IndexProjection, Zero, WrittenRows,
            AC + "S2 = (), 5\nArgCount(S2:0)",
            "1", 1,
            "unspread, the multi/zero-emitting projection still reifies as ONE written argument slot"),
        Raw("idx/list-target", IndexProjection, One, WrittenRows,
            "[10, 20, 30]:0",
            "10", 1,
            "indexing opens a list target through the projection view"),
        Shape("idx/list-element-opaque", IndexProjection, Two, WrittenRows,
            "[[1, 2], [3, 4]]:0",
            "L[#, #]", 1,
            "a selected list element is returned exactly as stored: one opaque list"),
        Err("idx/out-of-range", IndexProjection, Two, CaptureWrapped,
            "(1, 2):5",
            "index",
            "selection beyond the projected items is an index error"),

        // ── Builtin collection view (post-binding) ───────────────────────────
        Raw("view/empty-seq", BuiltinCollectionView, Zero, CaptureWrapped,
            "count(())",
            "0", 1,
            "the bound () collection opens to zero items"),
        Raw("view/empty-list", BuiltinCollectionView, Zero, WrittenRows,
            "count([])",
            "0", 1,
            "the bound [] collection opens to zero items"),
        Raw("view/scalar", BuiltinCollectionView, One, WrittenRows,
            "count(7)",
            "1", 1,
            "a non-collection value is a one-element collection"),
        Raw("view/two", BuiltinCollectionView, Two, CaptureWrapped,
            "count((1, 2))",
            "2", 1,
            "a bound two-item sequence opens to two items"),
        Raw("view/many", BuiltinCollectionView, Many, CaptureWrapped,
            "count((1, 2, 3))",
            "3", 1,
            "a bound three-item sequence opens to three items"),
        Raw("view/list-many", BuiltinCollectionView, Many, WrittenRows,
            "count([1, 2, 3])",
            "3", 1,
            "a bound list opens exactly like a bound sequence"),
        Raw("view/one-level-only", BuiltinCollectionView, Many, CaptureWrapped,
            "count((1, [2], 3))",
            "3", 1,
            "opening is never recursive: nested structures stay single items"),
        Raw("view/nested-empties", BuiltinCollectionView, Two, CaptureWrapped,
            "count(([], []))",
            "2", 1,
            "nested empty lists are two items"),
        Raw("view/string-opaque", BuiltinCollectionView, One, WrittenRows,
            "count('ab')",
            "1", 1,
            "a string is a one-element collection, never opened"),
        Raw("view/named-two", BuiltinCollectionView, Two, NamedReference,
            P + "count(P2)",
            "2", 1,
            "the named producer's captured sequence is the one collection argument"),
        Raw("view/named-empty", BuiltinCollectionView, Zero, NamedReference,
            P + "count(P0)",
            "0", 1,
            "the named () producer binds and opens to zero items"),
        Err("view/arity-multi", BuiltinCollectionView, Many, WrittenRows,
            "count(1, 2, 3)",
            "arity",
            "collection builtins are fixed-arity: three slots overflow count(collection)"),
        Err("view/arity-none", BuiltinCollectionView, Zero, WrittenRows,
            "count()",
            "arity",
            "zero slots underflow count(collection)"),
        Err("view/arity-spread", BuiltinCollectionView, Many, SpreadMarker,
            "count([1, 2, 3]*)",
            "arity",
            "spread supplies ordinary slots that obey the same fixed arity"),
        Err("view/take-missing-control", BuiltinCollectionView, Many, CaptureWrapped,
            "take((1, 2, 3))",
            "arity",
            "control parameters are fixed slots too: take needs (collection, count)"),
        Raw("view/regrouped-spreads", BuiltinCollectionView, Combo, SpreadMarker,
            P + "sum((P2*, P1*))",
            "37", 1,
            "re-grouping passes spread items as ONE collection argument: sum sees 10 + 20 + 7"),

        // ── Collection-producing builtin results (one exact list) ────────────
        Raw("cbr/take-two", CollectionBuiltinResult, Two, CaptureWrapped,
            "take((1, 2, 3), 2)",
            "L[1, 2]", 1,
            "kept items materialize as ONE exact list in order (makeCollectionListResult)"),
        Shape("cbr/take-one-kept-boundary", CollectionBuiltinResult, One, CaptureWrapped,
            "take(((1, 2), (3, 4)), 1)",
            "L[S[#, #]]", 1,
            "a single kept item is never erased: the one-item list boundary stays"),
        Shape("cbr/filter-none-kept", CollectionBuiltinResult, Zero, CaptureWrapped,
            "filter((1, 2), {x > 9})",
            "L[]", 1,
            "zero kept items form [] — still one emitted value"),
        Raw("cbr/filter-many", CollectionBuiltinResult, Many, CaptureWrapped,
            "filter((1, 2, 3), {x > 1})",
            "L[2, 3]", 1,
            "kept items preserve collection order"),
        Raw("cbr/map-preserves-count", CollectionBuiltinResult, Many, CaptureWrapped,
            "map((1, 2, 3), {x + 1})",
            "L[2, 3, 4]", 1,
            "map preserves element count and order"),
        Shape("cbr/map-empty-input", CollectionBuiltinResult, Zero, CaptureWrapped,
            "map((), {x + 1})",
            "L[]", 1,
            "an empty collection maps to [] without invoking the callback"),
        Shape("cbr/distinct-empties", CollectionBuiltinResult, Two, CaptureWrapped,
            "distinct(((), ()))",
            "L[S[]]", 1,
            "two equal () items collapse to one distinct element"),
        Shape("cbr/atoms-scalar", CollectionBuiltinResult, One, WrittenRows,
            "atoms(7)",
            "L[#]", 1,
            "atoms materializes one exact list regardless of input kind"),
        Raw("cbr/atoms-nested", CollectionBuiltinResult, Many, CaptureWrapped,
            "atoms((1, [2, [3]], 'x'))",
            "L[1, 2, 3]", 1,
            "atoms opens sequence AND list boundaries recursively, depth-first; strings contribute none"),
        Shape("cbr/atoms-string", CollectionBuiltinResult, Zero, WrittenRows,
            "atoms('ab')",
            "L[]", 1,
            "a string alone contributes no atoms: []"),
        Raw("cbr/range", CollectionBuiltinResult, Many, WrittenRows,
            "range(1, 3)",
            "L[1, 2, 3]", 1,
            "range materializes one exact list"),
        Shape("cbr/skip-all", CollectionBuiltinResult, Zero, CaptureWrapped,
            "skip((1, 2), 5)",
            "L[]", 1,
            "skipping past the end keeps zero items: []"),

        // ── Callback contracts ───────────────────────────────────────────────
        Err("cb/map-two-rows-rejected", CallbackContract, Two, BraceWrapped,
            "map((1, 2), {x, x})",
            "arity",
            "a map transform must emit exactly ONE value; two output rows are rejected (expectSingleMappedElement)"),
        Err("cb/map-empty-element-rejected", CallbackContract, Zero, BraceWrapped,
            "((), ()).map({x})",
            "arity",
            "a transform result of () is rejected: empty is not a mapped element"),
        Shape("cb/map-captured-pair-ok", CallbackContract, Two, CaptureWrapped,
            "map((1, 2), {(x, x)})",
            "L[S[#, #], S[#, #]]", 1,
            "capturing the two outputs into one sequence satisfies the single-value contract"),
        Shape("cb/map-empty-in-list-ok", CallbackContract, Zero, BraceWrapped,
            "((), ()).map({[x]})",
            "L[L[S[]], L[S[]]]", 1,
            "wrapping the () element in a list slot is one valid mapped value"),
        Err("cb/reduce-step-two-rejected", CallbackContract, Two, WrittenRows,
            "R2(x, acc) = 1, 2\nreduce((5), R2, 0)",
            "arity",
            "a reduce step must emit exactly one accumulator value (expectSingleAccumulator)"),
        Shape("cb/reduce-empty-initial-one-slot", CallbackContract, Two, NamedReference,
            "R(x, acc) = acc + x\nInit = 1, 2\nreduce((), R, Init)",
            "S[#, #]", 1,
            "the initial accumulator is ONE written slot (reCountValueBoundary): empty reduction returns it as one value"),
        Raw("cb/reduce-collecting-accumulator-slots", CallbackContract, Two, NamedReference,
            "App(item, *hist) = (hist*, item)\nInit = 1, 2\nreduce((9), App, Init)",
            "S[1, 2, 9]", 1,
            "a top-level collecting ACCUMULATOR parameter receives the accumulator's state slots: (1, 2) opens into hist = [1, 2] (evalSequenceReduceStepCounted)"),
        Err("cb/filter-nonatomic-rejected", CallbackContract, Two, CaptureWrapped,
            "filter((1, 2), {(x, x)})",
            "arity",
            "a filter predicate must return exactly one atomic truth value"),
        Raw("cb/param-projected-count", CallbackContract, Two, BraceWrapped,
            "((1, 2), (3, 4)).map({x.count})",
            "L[2, 2]", 1,
            "the callback parameter carries the whole element; count opens it one level"),
        Raw("cb/flat-multiparam-rows", CallbackContract, Many, WrittenRows,
            "Rows = (1, 2, 3), (4, 5, 6)\nF3(a, b, c) = a + b + c\nRows.map(F3)",
            "L[6, 15]", 1,
            "a flat multi-parameter callback opens a lone SEQUENCE element into row slots"),
        Err("cb/flat-multiparam-list-opaque", CallbackContract, Two, WrittenRows,
            "F2s(a, b) = a + b\n[[1, 2]].map(F2s)",
            "arity",
            "exact-list elements stay opaque in flat binding: one value cannot fill two parameters"),
        Raw("cb/collecting-callback-scalar", CallbackContract, One, WrittenRows,
            "CC(*i) = i.count\n[7].map(CC)",
            "L[1]", 1,
            "a single-collecting callback keeps each element as ONE collected slot"),
        Raw("cb/collecting-callback-pair", CallbackContract, Two, WrittenRows,
            "CC(*i) = i.count\n[(1, 2)].map(CC)",
            "L[1]", 1,
            "a sequence element is still ONE collected slot for a single-collecting callback"),
        Raw("cb/mixed-callback-rows", CallbackContract, Many, WrittenRows,
            "F(x, *y, z) = y.count\n((1, 2, 3, 4), (5, 6, 7)).map(F)",
            "L[2, 1]", 1,
            "sequence rows open, then prefix/collecting/suffix allocate per row"),
        Shape("cb/filter-keeps-exact", CallbackContract, Two, CaptureWrapped,
            "filter(((1, 2), 5), {x.count > 1})",
            "L[S[#, #]]", 1,
            "kept items are the original elements, exactly as collected"),
        Shape("cb/map-zero-elements-skips-contract", CallbackContract, Zero, CaptureWrapped,
            "map((), {x, x})",
            "L[]", 1,
            "with zero elements the transform never runs, so its would-be violation is unobserved"),

        // ── Loop state slots (while / repeat) ────────────────────────────────
        Raw("loop/repeat-two-state", LoopStateSlots, Two, WrittenRows,
            "repeat({a + 1, b + a}, 3, 0, 0)",
            "S[3, 3]", 2,
            "two initial slots, two step-output slots per iteration: the loop RESULT emits finalSlots.length = 2"),
        Raw("loop/repeat-one-state", LoopStateSlots, One, WrittenRows,
            "repeat({s + 1}, 3, 0)",
            "3", 1,
            "one state slot stays one slot: result emits 1"),
        Raw("loop/zero-iter-named-init-one-slot", LoopStateSlots, Two, NamedReference,
            P + "repeat({s}, 0, P2)",
            "S[10, 20]", 1,
            "an initial argument is ONE slot even when its value is a sequence: same value as the 2-slot form, count 1"),
        Raw("loop/zero-iter-spread-init-two-slots", LoopStateSlots, Two, SpreadMarker,
            P + "repeat({a + 1, b + a}, 0, P2*)",
            "S[10, 20]", 2,
            "a spread initial argument expands BEFORE the builtin binds: two slots (expandSequenceSpreadBuiltinArguments)"),
        Raw("loop/captured-init-one-slot", LoopStateSlots, Two, CaptureWrapped,
            "repeat({s}, 0, (10, 20))",
            "S[10, 20]", 1,
            "a captured pair is one initial state slot"),
        Raw("loop/step-spread-row-expands", LoopStateSlots, Two, SpreadMarker,
            P + "StepS(a, b) = P2*\nrepeat(StepS, 1, 0, 0)",
            "S[10, 20]", 2,
            "a flat step's spread output row contributes its items as separate next-state slots"),
        Raw("loop/patterned-step-packs-spread", LoopStateSlots, Two, Nested,
            "StepP((a, b)) = (a + 1, b + a)*\nrepeat(StepP, 3, (0, 0))",
            "S[3, 3]", 1,
            "a sequence-value-PATTERNED step keeps a top-level spread as ONE packed next-state slot — same value as the flat 2-slot loop, count 1"),
        Err("loop/step-shrink-arity", LoopStateSlots, Two, WrittenRows,
            "StepK(a, b) = a + b\nrepeat(StepK, 2, 1, 2)",
            "arity",
            "a step that shrinks the state to one slot cannot re-bind two parameters next iteration"),
        Raw("loop/step-shrink-final-ok", LoopStateSlots, One, WrittenRows,
            "StepK(a, b) = a + b\nrepeat(StepK, 1, 1, 2)",
            "3", 1,
            "shrinking on the LAST iteration is fine: one final slot, count 1"),
        Shape("loop/state-to-zero-slots", LoopStateSlots, Zero, SpreadMarker,
            P + "StepZ(s) = P0*\nrepeat(StepZ, 1, 5)",
            "S[]", 1,
            "a step spreading () leaves ZERO state slots; the loop result is () (count 0, clamped to one visible root slot)"),
        Shape("loop/state-to-zero-slots-spread-probe", LoopStateSlots, Zero, SpreadMarker,
            P + "StepZ(s) = P0*\nrepeat(StepZ, 1, 5)*",
            "S[]", 0,
            "spreading the zero-slot loop result supplies zero items — the 0-count is real"),
        Err("loop/state-zero-rebind-fails", LoopStateSlots, Zero, SpreadMarker,
            P + "StepZ(s) = P0*\nrepeat(StepZ, 2, 5)",
            "arity",
            "zero slots cannot re-bind the step parameter on the next iteration"),
        Raw("loop/collecting-step-grows", LoopStateSlots, Many, WrittenRows,
            "StepC(*hist) = hist*, 9\nrepeat(StepC, 2, 0)",
            "S[0, 9, 9]", 3,
            "a collecting step re-spreads its history and appends: state grows 1 → 2 → 3 slots"),
        Raw("loop/while-two-state", LoopStateSlots, Two, WrittenRows,
            "while({a + 1, b + a, a < 2}, 0, 0)",
            "S[2, 1]", 2,
            "while keeps multi-slot state; the final state emits its slot count"),
        Raw("loop/while-one-state", LoopStateSlots, One, WrittenRows,
            "while({s + 1, s < 3}, 0)",
            "3", 1,
            "one-slot while state emits one"),
        Raw("loop/empty-state-slot-visible", LoopStateSlots, Combo, WrittenRows,
            "StepE(a, b) = (), a\nrepeat(StepE, 1, 1, 2)",
            "S[S[], 1]", 2,
            "a () output row is one visible state slot"),

        // ── if boundary ──────────────────────────────────────────────────────
        Shape("if/branch-two", IfBoundary, Two, NamedReference,
            P + "if(1, P2, P1)",
            "S[#, #]", 1,
            "the chosen branch is one value boundary: two outputs arrive as one sequence (applyBuiltinCounted ifBuiltin re-counts)"),
        Shape("if/branch-empty", IfBoundary, Zero, NamedReference,
            P + "if(0, P2, P0)",
            "S[]", 1,
            "a () branch value re-counts to 0 and shows as one visible root slot"),
        Shape("if/branch-empty-spread-probe", IfBoundary, Zero, SpreadMarker,
            P + "if(0, P2, P0)*",
            "S[]", 0,
            "spreading the () if-result supplies zero items"),
        Raw("if/branch-one", IfBoundary, One, WrittenRows,
            "if(1, 7, 8)",
            "7", 1,
            "an atom branch is one value"),
        Shape("if/captured-branch", IfBoundary, Two, CaptureWrapped,
            "if(1, (10, 20), 5)",
            "S[#, #]", 1,
            "a captured branch argument is the same one value"),
        Shape("if/brace-branch-many", IfBoundary, Many, BraceWrapped,
            "if(1, {1, 2, 3}, 5)",
            "S[#, #, #]", 1,
            "a brace branch's three outputs cross the branch value boundary as one sequence"),
        Shape("if/result-spread-reopens", IfBoundary, Two, SpreadMarker,
            P + "if(1, P2, P1)*",
            "S[#, #]", 2,
            "explicit spread re-opens the if result"),
        Raw("if/cond-multi-first-atom", IfBoundary, Two, NamedReference,
            P + "if(P2, 1, 2)",
            "1", 1,
            "truth testing flattens the condition and reads its FIRST atom (Result.truthValue?): (10, 20) is true"),
        Raw("if/cond-zero-first-atom", IfBoundary, Combo, NamedReference,
            "Z0 = 0, 5\nif(Z0, 1, 2)",
            "2", 1,
            "the first flattened atom decides: (0, 5) is false"),
        Err("if/cond-empty-rejected", IfBoundary, Zero, NamedReference,
            P + "if(P0, 1, 2)",
            "arity",
            "() has no truth value"),
        Err("if/cond-list-rejected", IfBoundary, One, WrittenRows,
            "if([1], 1, 2)",
            "arity",
            "lists have no truth value (truth testing is sequence-only)"),
        Err("if/spread-arg-overflow", IfBoundary, Two, SpreadMarker,
            "Z1 = 1, 0\nif(Z1*, 5, 6)",
            "arity",
            "spread expands before the builtin arity check: four arguments overflow if(c, t, e)"),

        // ── List literal slots ───────────────────────────────────────────────
        Shape("list/empty", ListLiteralSlots, Zero, WrittenRows,
            "[]",
            "L[]", 1,
            "zero elements form the empty exact list — one value, never ()"),
        Shape("list/one-empty-element", ListLiteralSlots, Zero, NamedReference,
            P + "[P0]",
            "L[S[]]", 1,
            "a non-spread () slot is one exact element"),
        Shape("list/spread-empty", ListLiteralSlots, Zero, SpreadMarker,
            P + "[P0*]",
            "L[]", 1,
            "a spread () slot contributes no elements"),
        Shape("list/one", ListLiteralSlots, One, NamedReference,
            P + "[P1]",
            "L[#]", 1,
            "one slot, one element"),
        Shape("list/named-two-opaque", ListLiteralSlots, Two, NamedReference,
            P + "[P2]",
            "L[S[#, #]]", 1,
            "a named two-output producer is one element holding the whole sequence"),
        Shape("list/spread-two", ListLiteralSlots, Two, SpreadMarker,
            P + "[P2*]",
            "L[#, #]", 1,
            "a spread slot splices two elements into the list"),
        Shape("list/captured-element", ListLiteralSlots, Two, CaptureWrapped,
            "[(10, 20)]",
            "L[S[#, #]]", 1,
            "a captured pair is one exact element"),
        Shape("list/many", ListLiteralSlots, Many, WrittenRows,
            "[1, 2, 3]",
            "L[#, #, #]", 1,
            "three written slots, three elements"),
        Shape("list/combo", ListLiteralSlots, Combo, SpreadMarker,
            P + "[P0, P2*, P1]",
            "L[S[], #, #, #]", 1,
            "slots mix: a visible () element, two spliced items, one reified item"),
        Shape("list/nested-list-element", ListLiteralSlots, Two, Nested,
            "[[1, 2]]",
            "L[L[#, #]]", 1,
            "a nested list literal is one exact element — no flattening"),

        // ── Binary operator operand boundary ─────────────────────────────────
        Raw("op/empty-left-passthrough", OperatorOperandBoundary, Zero, NamedReference,
            P + "P0 + 5",
            "5", 1,
            "() is transparent for non-equality operators: the other operand passes through"),
        Raw("op/empty-right-passthrough", OperatorOperandBoundary, Zero, NamedReference,
            P + "5 + P0",
            "5", 1,
            "() passthrough is symmetric"),
        Raw("op/one", OperatorOperandBoundary, One, NamedReference,
            P + "P1 + 5",
            "12", 1,
            "an atom operand participates normally"),
        Err("op/seq-operand-rejected", OperatorOperandBoundary, Two, NamedReference,
            P + "P2 + 1",
            "type",
            "a multi-item sequence operand has no numeric value"),
        Err("op/many-operand-rejected", OperatorOperandBoundary, Many, NamedReference,
            P + "P3 + 1",
            "type",
            "three items are not a number either"),

        // ── Higher-order channel ─────────────────────────────────────────────
        Shape("ho/zero", HigherOrderChannel, Zero, NamedReference,
            P + "Call0(f) = f()\nCall0(P0)",
            "S[]", 1,
            "a zero-parameter value property invoked through the algorithm channel returns its () value"),
        Raw("ho/one", HigherOrderChannel, One, BraceWrapped,
            "Call0(f) = f()\nCall0({7})",
            "7", 1,
            "a one-output brace argument invoked by the callee returns one value"),
        Shape("ho/two-brace", HigherOrderChannel, Two, BraceWrapped,
            "Call0(f) = f()\nCall0({10, 20})",
            "S[#, #]", 1,
            "the invoked algorithm's two outputs cross the call's value boundary as one sequence"),
        Shape("ho/two-named", HigherOrderChannel, Two, NamedReference,
            P + "Call0(f) = f()\nCall0(P2)",
            "S[#, #]", 1,
            "a named producer passed as an argument invokes identically"),
        Shape("ho/many", HigherOrderChannel, Many, BraceWrapped,
            "Call0(f) = f()\nCall0({1, 2, 3})",
            "S[#, #, #]", 1,
            "three outputs, one value at the boundary"),
        Err("ho/capture-suppresses-identity", HigherOrderChannel, One, CaptureWrapped,
            "Inc(x) = x + 1\nApply1(f) = f(5)\nApply1((Inc))",
            "arity",
            "a capture exposes only a zero-parameter value thunk, never the contained callable identity"),

        // ── Nesting matrix (boundaries must not depend on AST depth) ─────────
        Shape("nest/producer-in-producer-spread", RootOutputRows, Many, Nested,
            P + "Q = P2*, P2*\nQ*",
            "S[#, #, #, #]", 4,
            "an inner spread flattens INSIDE the producer body; the outer spread re-opens all four"),
        Shape("nest/producer-in-producer-named", RootOutputRows, Combo, Nested,
            P + "Q2 = P2, P2\nQ2*",
            "S[S[#, #], S[#, #]]", 2,
            "inner named slots stayed opaque, so the outer spread opens exactly ONE boundary: two sequences"),
        Shape("nest/inner-capture-outer-rows", RootOutputRows, Two, Nested,
            P + "(P2*), P1",
            "S[S[#, #], #]", 2,
            "inner capture, outer direct: the capture is one row beside another"),
        Shape("nest/outer-capture-inner-direct", CaptureBoundary, Two, Nested,
            P + "((10, 20), P1*)",
            "S[S[#, #], #]", 1,
            "outer capture, inner boundaries as written: one value outside"),
        Shape("nest/both-captured", CaptureBoundary, Two, Nested,
            P + "((P2), (P2))",
            "S[S[#, #], S[#, #]]", 1,
            "both nested captures keep their boundaries"),
        Shape("nest/neither-captured", RootOutputRows, Many, Nested,
            P + "P2*, P2*",
            "S[#, #, #, #]", 4,
            "no boundaries anywhere: four root outputs"),
        Shape("nest/depth-independent-value", CaptureBoundary, Two, Nested,
            P + "(((P2*)))",
            "S[#, #]", 1,
            "extra redundant parens add no boundaries and change no counts"),
        Shape("nest/depth-independent-spread", SpreadSupply, Two, Nested,
            P + "(((P2)))*",
            "S[#, #]", 2,
            "spread through redundant parens still opens exactly one boundary"),
        Raw("nest/call-in-capture-in-spread", CallArgumentSlots, Combo, Nested,
            P + AC + "(ArgCount(P2*), P1)*",
            "S[2, 7]", 2,
            "a call result nests as one capture slot; the outer spread re-opens the capture"),
        Raw("nest/map-in-map", CallbackContract, Many, Nested,
            "((1, 2), (3, 4)).map({x.map({y + 1})})",
            "L[L[2, 3], L[4, 5]]", 1,
            "an inner map's one-list result is the outer transform's single mapped element"),
        Shape("nest/empty-in-empty", CaptureBoundary, Combo, Nested,
            P + "((P0, P0), P0)",
            "S[S[S[], S[]], S[]]", 1,
            "nested () slots stay visible at every level"),
        Shape("nest/spread-of-nested-empties", SpreadSupply, Combo, Nested,
            P + "(P0, P0)*",
            "S[S[], S[]]", 2,
            "spreading opens ONE boundary: two () items, not zero"),
        Shape("nest/spread-of-captured-empty-supply", SpreadSupply, Zero, Nested,
            P + "(P0*, P0*)*",
            "S[]", 0,
            "the capture is (); spreading it supplies zero items"),
    ];
}
