namespace KatLang.TestInfrastructure;

/// <summary>
/// One deliberate opt-in switch that lets a TARGETED test run rewrite a tracked
/// generated artifact. <see cref="Variable"/> is the exact environment-variable
/// name in its canonical upper-case spelling: Linux environments are
/// case-sensitive and this is the spelling the tests read, while Windows matches
/// names case-insensitively, which is why <c>scripts/validate-all.ps1</c> clears
/// the whole <see cref="RegenerationFlags.Prefix"/> namespace case-insensitively.
/// </summary>
internal sealed record RegenerationFlag(string Variable, string Regenerates)
{
    public override string ToString() => Variable;
}

/// <summary>
/// The registry of every regeneration flag in the repository.
///
/// <para>Adding a flag here is the ONLY way to introduce a new one: the policy
/// tests (<c>ArtifactRegenerationPolicyTests</c>) scan the repository for
/// <c>KATLANG_REGENERATE_*</c> tokens and fail on any that is not registered,
/// and they reject any test that reads a flag with anything but
/// <see cref="ArtifactRegeneration.VerifyOrRegenerate"/>. The verification
/// script does not need this list — it neutralizes the whole prefix — so a new
/// flag is governed the moment it exists.</para>
/// </summary>
internal static class RegenerationFlags
{
    /// <summary>The environment-variable namespace every regeneration flag lives in.</summary>
    public const string Prefix = "KATLANG_REGENERATE_";

    public static readonly RegenerationFlag LanguageSpec = new(
        Prefix + "LANGUAGE_SPEC",
        "lean/LanguageSpecCases.lean and the generated katlang-spec-examples block of both generator prompt files");

    public static readonly RegenerationFlag SemanticExplorer = new(
        Prefix + "SEMANTIC_EXPLORER",
        "lean/SemanticExplorerCases.lean");

    public static readonly RegenerationFlag PublicApi = new(
        Prefix + "PUBLIC_API",
        "tests/KatLang.Formatting.PublicApi.Tests/PublicApiBaseline.txt");

    public static readonly IReadOnlyList<RegenerationFlag> All = [LanguageSpec, SemanticExplorer, PublicApi];
}

/// <summary>
/// Thrown — as the intentional test failure — after a regeneration run has
/// written its artifact. Its type name in the test log says what happened:
/// the tree was rewritten, not verified.
/// </summary>
internal sealed class ArtifactRegeneratedException(RegenerationFlag flag, string artifactPath, string message)
    : Exception(message)
{
    public RegenerationFlag Flag { get; } = flag;
    public string ArtifactPath { get; } = artifactPath;
}

/// <summary>
/// The one regeneration contract for tracked generated artifacts (Lean corpora,
/// generator prompt blocks, the public API baseline).
///
/// <para><b>Normal verification is observational.</b> Without the flag a test
/// only compares the checked-in artifact with what it would generate and never
/// writes anything, so a green run means "tree verified", never "tree silently
/// rewritten".</para>
///
/// <para><b>Regeneration is explicit and fails by design.</b> With the flag set
/// to exactly <see cref="RequestedValue"/> in a targeted <c>dotnet test</c> run
/// the artifact is written (atomically, whole-file) and the test then throws
/// <see cref="ArtifactRegeneratedException"/> — even when the regenerated bytes
/// equal the checked-in ones — so the command that mutated the tree can never
/// report success. The developer reviews the diff, clears the flag, and reruns
/// the normal verification, which must pass.</para>
///
/// <para><b>validate-all never regenerates.</b> <c>scripts/validate-all.ps1</c>
/// removes every <c>KATLANG_REGENERATE_*</c> variable from its own process before
/// building or testing, so a flag inherited from the calling shell cannot turn
/// the verification command into a regeneration.</para>
/// </summary>
internal static class ArtifactRegeneration
{
    /// <summary>
    /// The only value that requests regeneration. Anything else (unset, empty,
    /// "0", "true", "yes") is verification mode, so the removal the script
    /// performs and any other value are equivalent; the script removes rather
    /// than blanks so that no consumer ever has to know this rule.
    /// </summary>
    public const string RequestedValue = "1";

    public static bool IsRequested(RegenerationFlag flag)
        => IsRequested(flag, Environment.GetEnvironmentVariable);

    internal static bool IsRequested(RegenerationFlag flag, Func<string, string?> environment)
        => environment(flag.Variable) == RequestedValue;

    /// <summary>
    /// Verifies the tracked artifact at <paramref name="artifactRelativePath"/>
    /// (repo-relative) with <paramref name="verify"/>, or — when
    /// <paramref name="flag"/> requests regeneration — writes the content
    /// produced by <paramref name="regenerate"/> to it and fails.
    /// </summary>
    /// <param name="afterRegenerating">
    /// An optional extra step for the failure message, phrased as an imperative
    /// clause (e.g. "run `lake build LanguageSpecCases` to check the Lean side").
    /// </param>
    public static void VerifyOrRegenerate(
        RegenerationFlag flag,
        string artifactRelativePath,
        Func<string> regenerate,
        Action verify,
        string? afterRegenerating = null)
        => Run(
            IsRequested(flag),
            flag,
            artifactRelativePath,
            Path.Combine(RepoRoot.Find(), artifactRelativePath),
            regenerate,
            verify,
            afterRegenerating);

    /// <summary>The policy itself, with the environment read factored out so it can be tested against a scratch path.</summary>
    internal static void Run(
        bool regenerationRequested,
        RegenerationFlag flag,
        string displayPath,
        string artifactPath,
        Func<string> regenerate,
        Action verify,
        string? afterRegenerating)
    {
        if (!regenerationRequested)
        {
            verify();
            return;
        }

        var content = regenerate();
        var previous = File.Exists(artifactPath) ? File.ReadAllText(artifactPath) : null;
        content = PreserveExistingLineEndings(previous, content);
        WriteAtomically(artifactPath, content);

        var outcome = previous is null
            ? "created"
            : previous == content
                ? "rewritten with identical content"
                : "updated";

        throw new ArtifactRegeneratedException(
            flag, artifactPath, DescribeRegeneration(flag, displayPath, outcome, afterRegenerating));
    }

    internal static string DescribeRegeneration(
        RegenerationFlag flag, string displayPath, string outcome, string? afterRegenerating)
        => $"Regenerated {displayPath} ({outcome}) because {flag.Variable}={RequestedValue} is set. " +
           "A regeneration run is not a verification run, so this test fails by design. " +
           $"Next: review the diff (git diff -- {displayPath})" +
           (afterRegenerating is null ? "" : $", {afterRegenerating}") +
           $", then clear the flag (PowerShell: Remove-Item Env:{flag.Variable}; sh: unset {flag.Variable}) " +
           "and rerun the normal verification, which must pass.";

    /// <summary>
    /// Regeneration should produce a reviewable content diff, not a Windows
    /// checkout whose only change is LF versus CRLF. Existing generated files
    /// therefore keep their established newline convention; a new artifact
    /// uses the generator's convention. Generated artifacts are text files and
    /// are expected to use one convention consistently.
    /// </summary>
    internal static string PreserveExistingLineEndings(string? previous, string content)
    {
        if (previous is null)
            return content;

        var firstLf = previous.IndexOf('\n');
        if (firstLf < 0)
            return content;

        var newLine = firstLf > 0 && previous[firstLf - 1] == '\r' ? "\r\n" : "\n";
        return content.ReplaceLineEndings(newLine);
    }

    /// <summary>
    /// Whole-file replacement through a sibling staging file: the artifact is
    /// either its previous content or the complete new content, never a partial
    /// write, and no staging file is left behind on failure.
    /// </summary>
    internal static void WriteAtomically(string path, string content)
    {
        var fullPath = Path.GetFullPath(path);
        var directory = Path.GetDirectoryName(fullPath)!;
        Directory.CreateDirectory(directory);

        var staging = Path.Combine(directory, $"{Path.GetFileName(fullPath)}.{Guid.NewGuid():N}.regenerating");
        try
        {
            File.WriteAllText(staging, content);
            File.Move(staging, fullPath, overwrite: true);
        }
        finally
        {
            if (File.Exists(staging))
                File.Delete(staging);
        }
    }
}

/// <summary>Locates the repository root (the directory holding KatLang.slnx) above the test output directory.</summary>
internal static class RepoRoot
{
    public static string Find()
    {
        var directory = AppContext.BaseDirectory;
        while (directory is not null && !File.Exists(Path.Combine(directory, "KatLang.slnx")))
            directory = Path.GetDirectoryName(directory);

        return directory
            ?? throw new InvalidOperationException("Could not locate repo root (KatLang.slnx) above test bin directory.");
    }
}
