using KatLang.Tests.AstGraphFuzz;

namespace KatLang.Tests;

/// <summary>
/// Deterministic structural AST-graph fuzz campaign (in-process oracle layer).
///
/// <para>Every case is a supported HOST-CONSTRUCTED expression DAG — including reference-shared
/// shapes ordinary source syntax cannot produce — generated by <see cref="AstGraphFuzzer"/> from
/// fixed seeds. For each case the campaign compares the SHARED graph against its fully expanded
/// CLONE and against every applicable evaluator entry point:</para>
///
/// <list type="bullet">
/// <item>structural-preflight verdict parity (shared vs cloned, repeated runs)</item>
/// <item>plain vs counted vs observed semantic parity (value, error kind, stable text)</item>
/// <item><c>RunFlat</c> as an exact function of <c>Run</c></item>
/// <item>counted emitted metadata parity</item>
/// <item>per-occurrence resource accounting: shared physical identity must not change consumed
/// steps, materialized items, or any resource verdict relative to the clone</item>
/// </list>
///
/// <para>The small-stack safety half of the campaign (every case executed on a 1 MiB thread in a
/// child process) lives in <c>AstGraphFuzzProcessTests</c>. Extended local runs:
/// <c>KATLANG_AST_FUZZ_SEED</c> (hex ok), <c>KATLANG_AST_FUZZ_CASES</c>, and
/// <c>KATLANG_AST_FUZZ_ONLY</c> (single case index) — normal CI never depends on entropy.</para>
/// </summary>
public class AstGraphFuzzTests
{
    internal const ulong DefaultSeed = 0x4B61744C616E6701UL;
    internal const int DefaultCaseCount = 160;

    /// <summary>Clone-expansion bound: cases whose expanded tree exceeds this skip the clone differential.</summary>
    private const long ClonedOccurrenceBound = 50_000;

    internal static ulong CampaignSeed
        => Environment.GetEnvironmentVariable("KATLANG_AST_FUZZ_SEED") is { Length: > 0 } text
            ? text.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
                ? ulong.Parse(text[2..], System.Globalization.NumberStyles.HexNumber)
                : ulong.Parse(text)
            : DefaultSeed;

    internal static int CampaignCaseCount
        => Environment.GetEnvironmentVariable("KATLANG_AST_FUZZ_CASES") is { Length: > 0 } text
            ? int.Parse(text)
            : DefaultCaseCount;

    internal static int? CampaignOnlyCase
        => Environment.GetEnvironmentVariable("KATLANG_AST_FUZZ_ONLY") is { Length: > 0 } text
            ? int.Parse(text)
            : null;

    // ── the per-case oracle ─────────────────────────────────────────────────

    /// <summary>
    /// Non-binding opt-in budgets for the ACCOUNTING pass: steps and cumulative materialization
    /// are only counted when configured, so the per-occurrence work parity oracle runs under
    /// generous ceilings no bounded campaign case can reach. (Configuring them pins the generic
    /// execution strategy — identically for the shared and cloned representations, which is
    /// exactly what the differential requires.)
    /// </summary>
    private static EvaluationLimits AccountingLimits { get; } = new()
    {
        MaxSteps = 50_000_000,
        MaxMaterializedItems = 50_000_000,
    };

    private sealed record Outcome(
        string Preflight,
        string? ErrorKind,
        string? ErrorText,
        Result? Value,
        int? EmittedCount,
        int PeakDepth,
        long ConsumedSteps,
        long MaterializedItems)
    {
        public bool Succeeded => ErrorKind is null && Preflight == "accepted";
    }

    private static string PreflightVerdict(Expr program)
    {
        var rejection = AstStructuralPreflight.Check(
            program, EvaluationLimits.MaxSupportedAstDepth, AstConsumerProfile.EvaluatorIterativeJoinSpines);
        return rejection is null ? "accepted" : rejection.Kind.ToString();
    }

    /// <summary>
    /// Evaluates one materialized program through the counted observed entry point and captures
    /// everything the oracles compare. Uses the observed variant so observer presence itself is
    /// part of what the parity oracles check against plain <c>Run</c>.
    /// </summary>
    private static Outcome Evaluate(Expr program, EvaluationLimits? limits = null)
    {
        var preflight = PreflightVerdict(program);
        var observations = new EvaluationObservations();
        var (result, budget) = Evaluator.RunCountedObserved(program, limits, observations: observations);

        return result.IsError
            ? new Outcome(
                preflight,
                result.Error.GetType().FullName,
                result.Error.ToString(),
                Value: null,
                EmittedCount: null,
                budget.PeakDepth,
                budget.ConsumedSteps,
                budget.MaterializedItems)
            : new Outcome(
                preflight,
                ErrorKind: null,
                ErrorText: null,
                result.Value.Value,
                result.Value.EmittedCount,
                budget.PeakDepth,
                budget.ConsumedSteps,
                budget.MaterializedItems);
    }

    private static void AssertOutcomesEquivalent(string context, Outcome expected, Outcome actual)
    {
        Assert.True(
            expected.Preflight == actual.Preflight,
            $"{context}: preflight verdict diverged: {expected.Preflight} vs {actual.Preflight}");
        Assert.True(
            expected.ErrorKind == actual.ErrorKind,
            $"{context}: error kind diverged: {expected.ErrorKind ?? "<ok>"} vs {actual.ErrorKind ?? "<ok>"}");
        Assert.True(
            expected.ErrorText == actual.ErrorText,
            $"{context}: error text diverged: {expected.ErrorText} vs {actual.ErrorText}");
        Assert.True(
            expected.EmittedCount == actual.EmittedCount,
            $"{context}: emitted count diverged: {expected.EmittedCount} vs {actual.EmittedCount}");
        if (expected.Value is not null || actual.Value is not null)
        {
            Assert.True(
                expected.Value is not null && actual.Value is not null
                    && Result.ValueComparer.Equals(expected.Value, actual.Value),
                $"{context}: values diverged: {expected.Value} vs {actual.Value}");
        }

        // Always-active dynamic-depth accounting must be identical: shared physical identity
        // must not change how many invocation levels were simultaneously active.
        Assert.True(
            expected.PeakDepth == actual.PeakDepth,
            $"{context}: peak depth diverged: {expected.PeakDepth} vs {actual.PeakDepth}");
        Assert.True(
            expected.ConsumedSteps == actual.ConsumedSteps,
            $"{context}: consumed steps diverged: {expected.ConsumedSteps} vs {actual.ConsumedSteps} "
            + "(shared physical identity must not change per-occurrence work)");
        Assert.True(
            expected.MaterializedItems == actual.MaterializedItems,
            $"{context}: materialized items diverged: {expected.MaterializedItems} vs {actual.MaterializedItems}");
    }

    /// <summary>
    /// Runs the full oracle bundle for one case; returns whether the clone differential ran.
    /// Every assertion message carries the replayable case description.
    /// </summary>
    internal static bool RunCaseOracles(GraphCase graphCase)
    {
        var replay = graphCase.Describe();

        // Safety valve: a case whose expanded occurrence count exceeds the bound would make
        // per-occurrence EVALUATION (not just the clone build) unboundedly expensive, so such
        // cases are checked at the verdict level only. The generator's per-node expansion cap
        // makes this branch unreachable for the CI corpus; it guards extended/custom seeds.
        if (AstGraphFuzzer.ExpandedOccurrenceCount(graphCase) > ClonedOccurrenceBound)
        {
            var bigShared = AstGraphFuzzer.WrapInProgram(AstGraphFuzzer.MaterializeShared(graphCase));
            Assert.Equal(PreflightVerdict(bigShared), PreflightVerdict(bigShared));
            return false;
        }

        // Shared representation, evaluated twice: identical immutable AST must produce an
        // identical verdict and identical accounting on repeated runs (and proves neither
        // preflight nor evaluation mutated the graph's later behavior).
        var shared = AstGraphFuzzer.WrapInProgram(AstGraphFuzzer.MaterializeShared(graphCase));
        var sharedOutcome = Evaluate(shared);
        var sharedAgain = Evaluate(shared);
        AssertOutcomesEquivalent($"repeat-run {replay}", sharedOutcome, sharedAgain);

        // Plain Run parity against the counted outcome.
        var plain = Evaluator.Run(shared);
        if (sharedOutcome.ErrorKind is null && sharedOutcome.Preflight == "accepted")
        {
            Assert.True(!plain.IsError, $"plain-vs-counted {replay}: plain errored {plain}");
            Assert.True(
                Result.ValueComparer.Equals(plain.Value, sharedOutcome.Value!),
                $"plain-vs-counted {replay}: value diverged: {plain.Value} vs {sharedOutcome.Value}");
        }
        else
        {
            Assert.True(plain.IsError, $"plain-vs-counted {replay}: plain succeeded where counted failed");
            Assert.True(
                plain.Error.GetType().FullName == sharedOutcome.ErrorKind
                    && plain.Error.ToString() == sharedOutcome.ErrorText,
                $"plain-vs-counted {replay}: error diverged: {plain.Error} vs {sharedOutcome.ErrorText}");
        }

        // RunFlat is exactly Run + bounded host flattening.
        var flat = Evaluator.RunFlat(shared);
        if (plain.IsError)
        {
            Assert.True(flat.IsError, $"flat {replay}: flat succeeded where plain failed");
            Assert.Equal(plain.Error.ToString(), flat.Error.ToString());
        }
        else
        {
            var limit = EvaluationLimits.Default.EffectiveMaxCollectionItems;
            if (plain.Value.TryToHostAtoms(limit, out var expectedAtoms))
            {
                Assert.True(
                    !flat.IsError,
                    $"flat {replay}: flat errored {(flat.IsError ? flat.Error.ToString() : "")}");
                Assert.Equal(expectedAtoms, flat.Value);
            }
            else
            {
                Assert.True(flat.IsError, $"flat {replay}: flatten-overflow did not surface");
                Assert.IsType<EvalError.CollectionSizeLimitExceeded>(flat.Error);
            }
        }

        // Shared-vs-cloned differential under default limits (always-active accounting).
        var cloned = AstGraphFuzzer.WrapInProgram(AstGraphFuzzer.MaterializeCloned(graphCase));
        var clonedOutcome = Evaluate(cloned);
        AssertOutcomesEquivalent($"shared-vs-cloned {replay}", sharedOutcome, clonedOutcome);

        // Shared-vs-cloned differential under configured (non-binding) step/materialization
        // budgets: this is where per-occurrence work parity becomes observable — a shared node
        // must charge once per semantic occurrence, exactly like its clones.
        var sharedAccounting = Evaluate(shared, AccountingLimits);
        var clonedAccounting = Evaluate(cloned, AccountingLimits);
        AssertOutcomesEquivalent($"shared-vs-cloned accounting {replay}", sharedAccounting, clonedAccounting);
        return true;
    }

    private static IEnumerable<int> CampaignCases()
    {
        if (CampaignOnlyCase is { } only)
        {
            yield return only;
            yield break;
        }

        for (var i = 0; i < CampaignCaseCount; i++)
            yield return i;
    }

    // ── the campaign ────────────────────────────────────────────────────────

    [Fact]
    public void Campaign_EveryCase_SatisfiesSharedClonedAndEntryPointOracles()
    {
        var seed = CampaignSeed;
        var clonedComparisons = 0;
        foreach (var index in CampaignCases())
        {
            if (RunCaseOracles(AstGraphFuzzer.Generate(seed, index)))
                clonedComparisons++;
        }

        if (CampaignOnlyCase is null)
        {
            Assert.True(
                clonedComparisons >= CampaignCaseCount * 9 / 10,
                $"only {clonedComparisons}/{CampaignCaseCount} cases were small enough for the clone differential");
        }
    }

    [Fact]
    public void Campaign_CoverageHistogram_ExercisesEveryKindAndKeyComposition()
    {
        var coverage = new AstGraphFuzzer.Coverage();
        for (var i = 0; i < DefaultCaseCount; i++)
            coverage.Accumulate(AstGraphFuzzer.Generate(DefaultSeed, i));

        foreach (var kind in Enum.GetValues<GKind>())
        {
            Assert.True(
                coverage.KindCounts.GetValueOrDefault(kind) >= 3,
                $"kind {kind} occurred only {coverage.KindCounts.GetValueOrDefault(kind)} times in the CI corpus");
        }

        Assert.True(coverage.SharedNodes >= 40, $"shared nodes: {coverage.SharedNodes}");
        Assert.True(coverage.RepeatedEdges >= 25, $"repeated edges: {coverage.RepeatedEdges}");
        Assert.True(coverage.DiamondJoins >= 40, $"diamond joins: {coverage.DiamondJoins}");
        Assert.True(
            coverage.SharedUnderDistinctParentKinds >= 20,
            $"shared under distinct parent kinds: {coverage.SharedUnderDistinctParentKinds}");
        Assert.True(
            coverage.SpreadOverConstructEdges >= 5,
            $"spread-over-construct alternations: {coverage.SpreadOverConstructEdges}");
        Assert.True(
            coverage.JoinToRecursiveHandoffs >= 10,
            $"join-to-recursive hand-offs: {coverage.JoinToRecursiveHandoffs}");
        Assert.True(
            coverage.SpineToNonSpineHandoffs >= 25,
            $"spine-to-non-spine hand-offs: {coverage.SpineToNonSpineHandoffs}");
        Assert.True(coverage.CaptureBoundaryNodes >= 25, $"capture boundaries: {coverage.CaptureBoundaryNodes}");
        Assert.True(
            coverage.SharedInCallArguments >= 8,
            $"shared nodes in call-argument slots: {coverage.SharedInCallArguments}");
    }

    [Fact]
    public void Generator_IsDeterministic_AndDescriptionsRoundTrip()
    {
        for (var i = 0; i < 24; i++)
        {
            var first = AstGraphFuzzer.Generate(DefaultSeed, i);
            var second = AstGraphFuzzer.Generate(DefaultSeed, i);
            Assert.Equal(first.Describe(), second.Describe());

            var described = first.Describe();
            var nodesPart = described[(described.IndexOf("v1 ", StringComparison.Ordinal) + 3)..];
            var reparsed = AstGraphFuzzer.Parse(first.Seed, first.CaseIndex, nodesPart);
            // GNode holds an ImmutableArray (reference-equality semantics), so round-trip
            // identity is asserted through the canonical description string.
            Assert.Equal(described, reparsed.Describe());
        }
    }

    // ── per-occurrence evaluation cost ──────────────────────────────────────

    /// <summary>
    /// Dynamic proof (not code inspection) that two semantic occurrences of ONE shared Expr
    /// cost more than one occurrence, and exactly what two cloned copies cost: shared physical
    /// identity must not introduce evaluate-once semantics anywhere in the evaluator.
    /// </summary>
    [Fact]
    public void SharedOccurrences_ChargePerOccurrence_ExactlyLikeClones()
    {
        // A user-call chain: admitted INVOCATIONS charge the step budget directly (builtins
        // deliberately charge no step, and bulk expression work is checkpoint-batched, so a
        // chargeable-work probe must be built from user calls).
        static Expr Work()
            => new Expr.Call(
                new Expr.Resolve("F"),
                [new Expr.Call(new Expr.Resolve("F"), [new Expr.Num(1)])]);

        static long StepsOf(params Expr[] outputRows)
        {
            var helpers = SourceProvenance.ParseValid(AstGraphFuzzer.HelperPreludeSource).Root;
            var program = new Expr.AlgorithmExpr(helpers with { Output = new OutputBundle(outputRows) });
            // Steps are counted only under a configured (here non-binding) step budget.
            var (result, budget) = Evaluator.RunCountedObserved(
                program, new EvaluationLimits { MaxSteps = 1_000_000 });
            Assert.False(result.IsError, result.IsError ? result.Error.ToString() : null);
            return budget.ConsumedSteps;
        }

        var shared = Work();
        var oneOccurrence = StepsOf(shared);
        var twoSharedOccurrences = StepsOf(shared, shared);
        var twoClonedOccurrences = StepsOf(Work(), Work());

        Assert.True(
            twoSharedOccurrences > oneOccurrence,
            $"two occurrences of one shared Expr cost {twoSharedOccurrences} steps, "
            + $"not more than one occurrence's {oneOccurrence}");
        Assert.Equal(twoClonedOccurrences, twoSharedOccurrences);
    }

    // ── Algorithm-vs-Sequence boundary invariants ───────────────────────────

    /// <summary>
    /// Multiple algorithm outputs and one Sequence value are NOT interchangeable, and the
    /// fuzzer's domain must keep exercising the distinction: a zero-declaration block argument
    /// reifies to ONE value slot at a builtin boundary, a capture bundles rows into one
    /// sequence value, and separate written argument slots stay separate.
    /// </summary>
    [Fact]
    public void AlgorithmOutputsVersusSequenceValues_KeepDistinctArity()
    {
        static EvalResult<Result> Run(Expr root)
            => Evaluator.Run(AstGraphFuzzer.WrapInProgram(root));

        // count((1, 2, 3)) — one captured sequence argument: 3 items.
        var capturedArg = Run(new Expr.Call(
            new Expr.Resolve("count"),
            [new Expr.Capture([new Expr.Num(1), new Expr.Num(2), new Expr.Num(3)])]));
        Assert.False(capturedArg.IsError);
        Assert.Equal([3m], capturedArg.Value.ToAtoms());

        // count(1, 2, 3) — three separate argument slots: fixed-arity error.
        var separateArgs = Run(new Expr.Call(
            new Expr.Resolve("count"),
            [new Expr.Num(1), new Expr.Num(2), new Expr.Num(3)]));
        Assert.True(separateArgs.IsError);
        Assert.Contains("count", separateArgs.Error.ToString(), StringComparison.OrdinalIgnoreCase);

        // count({1 2 3}) — a zero-declaration block argument reifies to ONE value slot.
        var blockArg = Run(new Expr.Call(
            new Expr.Resolve("count"),
            [
                new Expr.AlgorithmExpr(new Algorithm.User(
                    null, [], [], [],
                    [new Expr.Num(1), new Expr.Num(2), new Expr.Num(3)])),
            ]));
        Assert.False(blockArg.IsError);
        Assert.Equal([3m], blockArg.Value.ToAtoms());

        // Root emission: two output rows emit 2; one capture of the same rows emits 1.
        var helpers = SourceProvenance.ParseValid(AstGraphFuzzer.HelperPreludeSource).Root;
        var twoRows = Evaluator.RunCounted(new Expr.AlgorithmExpr(
            helpers with { Output = new OutputBundle([new Expr.Num(1), new Expr.Num(2)]) }));
        Assert.False(twoRows.IsError);
        Assert.Equal(2, twoRows.Value.EmittedCount);

        var oneCapture = Evaluator.RunCounted(new Expr.AlgorithmExpr(
            helpers with { Output = new OutputBundle([new Expr.Capture([new Expr.Num(1), new Expr.Num(2)])]) }));
        Assert.False(oneCapture.IsError);
        Assert.Equal(1, oneCapture.Value.EmittedCount);
        Assert.Equal([1m, 2m], oneCapture.Value.Value.ToAtoms());
    }

    // ── value-DAG payload family ────────────────────────────────────────────

    /// <summary>
    /// The helper scope's <c>D</c> is a shared Result DAG (the doubling recipe at depth 6:
    /// 64 semantic leaf paths over O(depth) physical nodes). Generated ASTs consume it through
    /// equality, projection, and counting; this pins the deterministic expected values so the
    /// random family's oracle comparisons rest on verified ground.
    /// </summary>
    [Fact]
    public void ValueDagHelpers_HaveTheExpectedShape()
    {
        static Result Eval(Expr root)
        {
            var r = Evaluator.Run(AstGraphFuzzer.WrapInProgram(root));
            Assert.False(r.IsError, r.IsError ? r.Error.ToString() : null);
            return r.Value;
        }

        var d = new Expr.Resolve("D");
        Assert.Equal([1m], Eval(new Expr.Binary(BinaryOp.Eq, d, d)).ToAtoms());
        Assert.Equal([2m], Eval(new Expr.DotCall(d, "count")).ToAtoms());
        Assert.Equal(
            [64m],
            Eval(new Expr.Call(
                new Expr.Resolve("count"),
                [new Expr.Call(new Expr.Resolve("atoms"), [d])])).ToAtoms());
    }

    // ── deterministic reducer ───────────────────────────────────────────────

    /// <summary>
    /// Permanent reducer exercise: minimizes a generated case against a synthetic failure
    /// predicate ("the shared program is depth-rejected under a tiny limit") and proves the
    /// minimized description still fails, is small, and replays identically from its printed
    /// form. This keeps the shrinking path working so a real future finding arrives minimized.
    /// </summary>
    [Fact]
    public void Reducer_MinimizesAFailingCase_AndReplaysDeterministically()
    {
        static bool Fails(GraphCase candidate)
        {
            var program = AstGraphFuzzer.WrapInProgram(AstGraphFuzzer.MaterializeShared(candidate));
            return AstStructuralPreflight.Check(
                program, maxDepth: 20, AstConsumerProfile.EvaluatorIterativeJoinSpines) is not null;
        }

        // Deterministically find the first CI-corpus case that fails the synthetic predicate.
        GraphCase? failing = null;
        for (var i = 0; i < DefaultCaseCount && failing is null; i++)
        {
            var candidate = AstGraphFuzzer.Generate(DefaultSeed, i);
            if (Fails(candidate))
                failing = candidate;
        }

        Assert.NotNull(failing);
        var reduced = AstGraphFuzzer.Reduce(failing, Fails);

        Assert.True(Fails(reduced), "reduced case no longer fails the predicate");
        Assert.True(
            reduced.Nodes.Length <= 12,
            $"reducer left {reduced.Nodes.Length} nodes: {reduced.Describe()}");
        Assert.True(
            reduced.Nodes.Length <= failing.Nodes.Length,
            "reducer must never grow the case");

        // Round-trip replay of the minimized description.
        var described = reduced.Describe();
        var nodesPart = described[(described.IndexOf("v1 ", StringComparison.Ordinal) + 3)..];
        var replayed = AstGraphFuzzer.Parse(reduced.Seed, reduced.CaseIndex, nodesPart);
        Assert.Equal(described, replayed.Describe());
        Assert.True(Fails(replayed), "replayed minimized case must still fail");
    }

    // ── deterministic cycle rejection (classification coverage) ─────────────

    [Fact]
    public void CyclicHostGraph_IsRejectedAsStructuredCycleError()
    {
        // The one supported cycle seam: an Algorithm's caller-owned Opens list.
        var opens = new List<Expr>();
        var block = new Expr.AlgorithmExpr(new Algorithm.User(null, [], opens, [], [new Expr.Num(1)]));
        var cyclic = new Expr.Call(block, [new Expr.Num(1)]);
        opens.Add(cyclic);

        var result = Evaluator.Run(cyclic);
        Assert.True(result.IsError);
        Assert.IsType<EvalError.AstCycleDetected>(result.Error);
    }
}
