import Lake
open Lake DSL

package «katlang»

@[default_target]
lean_lib «KatLang» where
  srcDir := "."

lean_lib «CoreTests» where
  srcDir := "."

lean_lib «AstDemo» where
  srcDir := "."

lean_lib «KatLangArityLaws» where
  srcDir := "."

-- Isolated arity-algebra model extracted from `KatLang.lean` (paper artifact).
-- Self-contained: it does not import `KatLang`, so it cannot affect the
-- authoritative model.
lean_lib «CoreArityAlgebra» where
  srcDir := "."

lean_lib «CoreArityAlgebraProofs» where
  srcDir := "."

-- Generated Lean/C# differential corpus for the small-state semantic explorer.
-- Regenerated by tests/KatLang.Tests/SemanticExplorerLeanArtifactTests.cs;
-- a failing #guard here is a Lean/C# divergence on that corpus case.
lean_lib «SemanticExplorerCases» where
  srcDir := "."

-- Generated Lean half of the canonical executable language specification.
-- Regenerated by tests/KatLang.Tests/LanguageSpec/LanguageSpecLeanArtifactTests.cs;
-- each #guard pins a CANONICAL expectation from LanguageSpecCorpus.cs (the C#
-- runner pins the same expectation against the C# engine).
lean_lib «LanguageSpecCases» where
  srcDir := "."
